// тут будут жить наши константы типов
export const LIKES_INCREMENT = 'LIKE/LIKES_INCREMENT'
export const LIKES_DECREMENT = 'LIKE/LIKES_DECREMENT'
export const AUTH_FORM_VISIBLE = 'AUTH/AUTH_FORM_VISIBLE'
export const AUTH_FORM_REGESTERD = 'AUTH/AUTH_FORM_REGESTERED'
export const CALC_VISIBLE = 'CALC/CALC_VISIBLE'
export const CALC_ISCLICKED = 'CALC/CALC_ISCLICKED'
export const CALC_ONCHANGE = 'CALC/CALC_ONCHANGE'